### ISSUE TITLE
Update to poetry 1.2.0

### ISSUE THREAD

**Issue by allenlawrence94** [CircleCI-Public/python-orb#103]
## Describe Request:
The latest poetry has some nice new features. It would be great if this project could soon migrate to poetry 1.2.0. so that we can use these new features in CircleCI.

## Examples:
- generalized dependency groups

## Supporting Documentation Links:
https://python-poetry.org/blog/announcing-poetry-1.2.0/

**Comment by ilaner** [comment]
Will be much appreciated.
We added the following configuration for a workaround to support poetery 1.2.0:
`pre-install-steps:
          - run:
              # this is a workaround until circleci will support poetry 1.2.0
              name: Update poetry
              command: |
                poetry self update
`

**Comment by Jaryt** [comment]
Hi! The python-orb does not manage the poetry version. There has been a issue opened on `cimg-python` for this: https://github.com/CircleCI-Public/cimg-python/issues/145
