### ISSUE TITLE
Add parameter to specify poetry version

### ISSUE THREAD

**Issue by AMontagu** [CircleCI-Public/python-orb#109]
## Orb version:

circleci/python@2.1.1

## What happened:
With last release of poetry 1.13.0 they change the lock-version and make it not working in ci. Can we update poetry version in the orbs ?

https://app.circleci.com/pipelines/github/socotecio/django-socio-grpc/692/workflows/5f5e7d8a-51af-4016-9e7a-a10aac024cbc/jobs/789

## Expected behavior:

ci working with lock-verison 2.0

## Additional Information:

[metadata]
lock-version = "2.0"
python-versions = ">=3.8,<4.0"

**Comment by dsayling** [comment]
@AMontagu - the poetry version is always the latests at the release of the [cimg](https://github.com/CircleCI-Public/cimg-python)

If you need to specify a different poetry version, you can either use a step to just pip install the version you'd like before running the orb commands, or, if using the test job, you can specify the same pip install a pre-install-steps list.

**Comment by AMontagu** [comment]
Strange it looked to be not the latest version in the orbs at the time.
I actually changed the CI system to use github actions now so I will not be able to reproduce or validate. 
Will close this.
