### ISSUE TITLE
Support for Poetry operating modes - non-package mode

### ISSUE THREAD

**Issue by hwilliamsoctopus** [CircleCI-Public/python-orb#119]
## Orb version:
2.1.1

## What happened:
When installing poetry, it doesn't respect the `package-mode = false` from the poetry config, and therefore expects the optional fields to be provided, causing the error:
```
'name'

Exited with code exit status 1
```

I am not trying to publish the package, just use it for dependency management and therefore this shouldn't fail.

## Expected behavior:
It should install without any of the optional fields that are not needed in `package-mode = false`. These are outlined in the poetry documentation as well

## Additional Information:
New mode:
https://python-poetry.org/docs/basic-usage/#operating-modes

Now optional fields:
https://python-poetry.org/docs/pyproject/

**Comment by marboledacci** [comment]
I don't understand how is this related to the orb, the only poetry related command is `poetry install --no-ansi << parameters.args >>` is there something to do here that cannot be passed with the args?
