### ISSUE TITLE
Coverage using wrong python version

### ISSUE THREAD

**Issue by sergiosbx** [CircleCI-Public/python-orb#42]
Hello,

When I run the Coverage command, it tries to obtain python version 3.8.4, but the installed version of Orb is 3.8.5.

Is it possible to configure the image so that it gets the correct version?

Thank you.

![image](https://user-images.githubusercontent.com/8169195/89299990-e7e33e00-d63d-11ea-82f4-9c5cf7a36ef2.png)

Orb version: circleci/python@0.3.2

**Comment by dsayling** [comment]
@sergiosbx, the pyenv cache is versioned - you may need to invalidate the cache if you moved to a new version, or set your executor in your config to use the 3.8.4 image
