### ISSUE TITLE
'test' command should store_test_results

### ISSUE THREAD

**Issue by dawngerpony** [CircleCI-Public/python-orb#45]
## Describe Request:

- the orb has a `test` command
- the command runs `pytest` by default, but does not use the `store_test_results` command to store test results against the build
- it would be great if the `test` command could default to generating JUnit-style XML test results in a file, then storing those test results against the build

## Examples:

- `pytest --junitxml=./test-results.xml`

## Supporting Documentation Links:

- https://circleci.com/orbs/registry/orb/circleci/python#commands-test
- https://docs.pytest.org/en/stable/usage.html#creating-junitxml-format-files
- https://circleci.com/docs/2.0/configuration-reference/#store_test_results

**Comment by dsayling** [comment]
This feature was added in the 1.0.0 release of the orb!

**Comment by dawngerpony** [comment]
Thank you @dsayling 🙌
