### ISSUE TITLE
Add an example passing parameters to the install-deps command

### ISSUE THREAD

**Issue by jlgimeno** [CircleCI-Public/python-orb#46]
## Describe Request:
Occasionally repos are set up with a different requirements file than requirements.txt.  There is no documentation for passing parameters to commands in orbs

## Examples:
From my own config.yml:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps:
          dependency-file: dev-requirements.txt
          local: true
      - python/save-cache

There was no documentation that both parameters had to be passed, even if one of them remains the default (local in this case).  This would save a considerable amount of time to users that are not aware of this requirements.

**Comment by dsayling** [comment]
Hi there! The documentation was lacking prior to the 1.0.0 release of the orb. With the latest release, you'll find better examples, however the ability to specify a requirements.txt was removed. In the PR linked, I have added the ability to specify a different requirements.txt or even a setup.py to be used in the command.
