### ISSUE TITLE
Proposal: change test-tool default to pytest

### ISSUE THREAD

**Issue by circlecai** [CircleCI-Public/python-orb#84]
## Describe Request: We would like to change the default test tool to pytest, so that more people get test reports automatically. 

pytest can run unittest tests in most cases, and it will automatically produce test reports; unittest cannot produce test reports.

The disadvantage is that the transition would not be perfect; if there are projects that are running unittest tests that use the load_tests protocol or subtests then if they update the orb to the new version without reading the docs it may be surprising that they need add an explicit `test-tool: unittest` parameter.

## Supporting Documentation Links: 

https://docs.pytest.org/en/6.2.x/unittest.html

**Comment by KyleTryon** [comment]
Not sure if @dsayling would be interested in commenting (I believe even though he doesn't work on the orb anymore he may still be using it) but I'd love to hear their thoughts.

**Comment by dsayling** [comment]
Another issue would be including the dependency. If the user doesn't have pytest specified in their Pipfile, pyproject.toml, or requirements file the job would either have to install it if not present or notify the user to specify the dependency themselves. I suppose there shouldn't be an issue trying to add it at run time, but it would definitely necessitate a 2.0 release for the orb.

**Comment by Jaryt** [comment]
I think the points here are good and I agree with Drew that this would certainly require a 2.0 release as this would be a breaking change. @KyleTryon I wonder if you have any more thoughts on this. 

If you think we should move forward with this, then we should give the orb the major release treatment and try and get all of these issues solved out within that release.
