### ISSUE TITLE
Error saving and restoring pyenv cache from a machine executor

### ISSUE THREAD

**Issue by carlosjgp** [CircleCI-Public/python-orb#99]
## Orb version:
`2.0.3`

## What happened:
```
error computing cache key: template: cacheKey:1:75: executing "cacheKey" at <checksum "/home/circleci/.pyenv/version">: error calling checksum: open /home/circleci/.pyenv/version: no such file or directory
```
![image](https://user-images.githubusercontent.com/1277613/161747404-d4c19d9b-e451-4698-b457-68d3e9d0d5fb.png)

## Expected behavior:

Cache is restored and saved correctly

## Additional Information:
Using executor machine
`ubuntu-2004:202111-02`

The `pyenv root` seems to be on `/opt/circleci/.pyenv` on this particular machine

**Comment by carlosjgp** [comment]
More context

We are actually using the `poetry` command
![image](https://user-images.githubusercontent.com/1277613/161761989-03d67338-4f17-4806-99a3-025919b3b677.png)

**Comment by Jaryt** [comment]
Hi Carlos! Sorry for the delay here. I see that we are not covering our tests on machine for the python Orb. I will fix this issue and ensure that we're testing on machine as well.

**Comment by mlhamel** [comment]
Any news on this end? we are experiencing the same with different projects and all of them are also based on `poetry`

**Comment by Jaryt** [comment]
> Any news on this end? we are experiencing the same with different projects and all of them are also based on `poetry`

Will have this resolved within the next week. Thank you for your patience!

**Comment by Jaryt** [comment]
Hello! @dhuckins introduced a pr to remove the dependency of the pyenv version file. I didn't catch that we did not have that updated for the save step, and have fixed that in #105 

This will be available in v2.1.1

**Comment by dhuckins** [comment]
@Jaryt didn't see that, thanks for fixing!

**Comment by Jaryt** [comment]
> @Jaryt didn't see that, thanks for fixing!

You got it!
